sudo: false
language: python
python: '3.5'
env:
- TOXENV=flake8
- TOXENV=markdown-lint
- TOXENV=linkchecker
- TOXENV=jshint
- TOXENV=csslint
- TOXENV=py26-integration
- TOXENV=py26-min-req
- TOXENV=py26-unittests
- TOXENV=py27-integration
- TOXENV=py27-min-req
- TOXENV=py27-unittests
- TOXENV=py33-integration
- TOXENV=py33-min-req
- TOXENV=py33-unittests
- TOXENV=py34-integration
- TOXENV=py34-min-req
- TOXENV=py34-unittests
- TOXENV=py35-integration
- TOXENV=py35-min-req
- TOXENV=py35-unittests
- TOXENV=pypy-integration
- TOXENV=pypy-min-req
- TOXENV=pypy-unittests
- TOXENV=pypy3-integration
- TOXENV=pypy3-min-req
- TOXENV=pypy3-unittests
install:
- pip install tox
- gem install mdl
- npm install -g jshint
- npm install -g csslint
script:
- git clean -f -d -x
- tox
matrix:
  allow_failures:
    - env: TOXENV=pypy3-integration
    - env: TOXENV=pypy3-min-req
    - env: TOXENV=pypy3-unittests
before_install: pip install codecov
after_success: codecov
deploy:
  provider: pypi
  user: mkdocsdeploy
  distributions: "sdist bdist_wheel"
  password:
    secure: b4f6y1xw5B/RXXnOu6JIaNcgOBZ0/CkNaMeEXsoQSewYZNwobLPYALY9WaaOblarwrVa5NRD3e4x6SoL1/1NzQxfhCNMn7L82sssmtevnK+mSuUp4IZQa8WKyz+xLfnk28TlHgQbctAU9NaeQ6GuEflTRD7Bp8+xJ1C7h+yBUnw=
  on:
    tags: true
    repo: mkdocs/mkdocs
    condition: "$TOXENV = py27-integration"
