sudo: false
language: python
python: '2.7'
env:
- TOXENV=py26-integration
- TOXENV=py26-min-req
- TOXENV=py26-unittests
- TOXENV=py27-integration
- TOXENV=py27-min-req
- TOXENV=py27-unittests
- TOXENV=py33-integration
- TOXENV=py33-min-req
- TOXENV=py33-unittests
- TOXENV=py34-integration
- TOXENV=py34-min-req
- TOXENV=py34-unittests
- TOXENV=py35-integration
- TOXENV=py35-min-req
- TOXENV=py35-unittests
- TOXENV=pypy-integration
- TOXENV=pypy-min-req
- TOXENV=pypy-unittests
- TOXENV=pypy3-integration
- TOXENV=pypy3-min-req
- TOXENV=pypy3-unittests
- TOXENV=flake8
- TOXENV=markdown-lint
install:
- pip install tox
- gem install mdl
script:
- git clean -f -d -x
- tox
matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=markdown-lint
before_install: pip install codecov
after_success: codecov
