build: false
environment:
  matrix:
    - TOXENV: py33-integration
    - TOXENV: py33-min-req
    - TOXENV: py33-unittests
    - TOXENV: py34-integration
    - TOXENV: py34-min-req
    - TOXENV: py34-unittests
    - TOXENV: flake8
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:\\Python*"
install:
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - "c:\\python27\\python c:\\ez_setup.py"
  - "c:\\python27\\python c:\\get-pip.py"
  - "c:\\python27\\Scripts\\pip install tox"
test_script:
  - "git clean -f -d"
  - "c:\\python27\\Scripts\\tox --version"
  - "c:\\python27\\Scripts\\pip --version"
  - "c:\\python27\\Scripts\\tox"
