build: false
environment:
  matrix:
    - TOXENV: py27-integration
    - TOXENV: py27-min-req
    - TOXENV: py27-unittests
    - TOXENV: py33-integration
    - TOXENV: py33-min-req
    - TOXENV: py33-unittests
    - TOXENV: py34-integration
    - TOXENV: py34-min-req
    - TOXENV: py34-unittests
    - TOXENV: py35-integration
    - TOXENV: py35-min-req
    - TOXENV: py35-unittests
    - TOXENV: py36-integration
    - TOXENV: py36-min-req
    - TOXENV: py36-unittests
    - TOXENV: flake8
init:
  - "ECHO %TOXENV%"
install:
  - "c:\\python27\\Scripts\\pip install tox"
test_script:
  - "git clean -f -d -x"
  - "c:\\python27\\Scripts\\tox --version"
  - "c:\\python27\\Scripts\\pip --version"
  - "c:\\python27\\Scripts\\tox"
