site_name: MkDocs
site_url: http://www.mkdocs.org/
site_description: Project documentation with Markdown.

repo_url: https://github.com/tomchristie/mkdocs/

dev_addr: 0.0.0.0:8000

pages:
- ['index.md', 'Home']
- ['user-guide/index.md', '**HIDDEN**']
- ['user-guide/index2.md', '**HIDDEN**']
- ['user-guide/writing-your-docs.md', 'User Guide', 'Writing your docs']
- ['user-guide/styling-your-docs.md', 'User Guide', 'Styling your docs']
- ['user-guide/configuration.md', 'User Guide', 'Configuration']
- ['about/index.md', '**HIDDEN**']
- ['about/license.md', 'About', 'License']

copyright: Copyright &copy; 2014, <a href="https://twitter.com/_tomchristie">Tom Christie</a>.
google_analytics: ['UA-27795084-5', 'mkdocs.org']
